### ISSUE TITLE
Ch2 Training & Evaluating on training set: fit_transform instead of transform

### ISSUE THREAD

**Issue by thor4** [ageron/handson-ml#29]
After training a Linear Regression model and loading some data to try it out on, I received the following error:

    some_data_prepared = full_pipeline.transform(some_data)
    Traceback (most recent call last):

    File "<ipython-input-10-ce624cfb8912>", line 2, in <module>
        some_data_prepared = full_pipeline.transform(some_data)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 763, in transform
        for name, trans, weight in self._iter())

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 758, in 
    __call__
        while self.dispatch_one_batch(iterator):

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 608, in 
    dispatch_one_batch
        self._dispatch(tasks)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 571, in 
    _dispatch
        job = self._backend.apply_async(batch, callback=cb)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 
    109, in apply_async
        result = ImmediateResult(func)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 
    326, in __init__
        self.results = batch()

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in 
    __call__
        return [func(*args, **kwargs) for func, args, kwargs in self.items]

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in 
    <listcomp>
        return [func(*args, **kwargs) for func, args, kwargs in self.items]

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 567, in _transform_one
        res = transformer.transform(X)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\pipeline.py", line 445, in _transform
        Xt = transform.transform(Xt)

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\preprocessing\imputation.py", line 311, in 
    transform
        check_is_fitted(self, 'statistics_')

    File "C:\Users\bryan\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 690, in 
    check_is_fitted
        raise _NotFittedError(msg % {'name': type(estimator).__name__})

    NotFittedError: This Imputer instance is not fitted yet. Call 'fit' with appropriate arguments before 
    using this method.`

I changed the method to fit_transform and it worked fine. 

`some_data_prepared = full_pipeline.fit_transform(some_data)`

Perhaps the code in the notebook should be updated accordingly?

**Update**
My suggestion yields some_data_prepared with a shape of (5,14) which will *not* allow for the predict method to run due to shapes not aligning.

Instead, the imputer instance needed to be fit separately before running the transform method of full_pipeline on some_data.

    imputer = Imputer(strategy="median")
    imputer.fit(housing_num)

 If users went through the chapter entering all the code as instructed, this would not be an issue. I had closed out and come back to it, losing the fit imputer instance in the process.

**Comment by ageron** [comment]
Hi @thor4 ,

Thanks for your feedback.  Your explanation seems right: if you closed the notebook, then everything that was in memory was lost, in particular the trained model, which would explain why it crashed when running `transform()`. The correct solution is to run the notebook up to the point you are interested in (as you did).
Replacing `transform()` with `fit_transform()` would not be the correct solution, as you would be fitting your model to test instances, which is almost never what you want to do: you want to train your model on training data.

Hope this helps,
Aurélien
