### ISSUE TITLE
MemoryError with "scaler.fit_transform(X_train.astype(np.float64))" with a separate script

### ISSUE THREAD

**Issue by samaujs** [ageron/handson-ml#357]
Hi Ageron,

I have tried to create a separate python script file and execute as per "luvaihassanali" comments on a "Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1032-aws x86_64)" machine, running Python 3.6.7.  But, I still have the same MemoryError problem with outputs even not running in Jupyter notebook and as follow :

Traceback (most recent call last):
File "mnist_test.py", line 35, in 
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/base.py", line 462, in fit_transform
return self.fit(X, **fit_params).transform(X)
File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 625, in fit
return self.partial_fit(X, y)
File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 649, in partial_fit
force_all_finite='allow-nan')
File "/home/ubuntu/ml/VirtualEnv/env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 598, in check_array
array = np.array(array, dtype=dtype, order=order)
MemoryError

**Comment by ageron** [comment]
Sorry for the late response. Are you still experiencing this issue?

**Comment by samaujs** [comment]
Thanks Ageron for reaching out, it has been resolved.

**Comment by ageron** [comment]
Closing the issue since it has been resolved. If you could explain what solved the issue, that would be great for other people who run into it. Thanks!

**Comment by samaujs** [comment]
Hi Ageron, it was resolved using a new AWS t2 instance with larger memory space.  It must be running out of memory due to the type conversion.  Cheers.
